// react-app/src/components/Header.js
import React, { useState, useRef, useEffect } from "react";
import { ReactComponent as LoginSVG } from "../assets/Lock.svg";
import { ReactComponent as SignupSVG } from "../assets/Add-User.svg";
import { ReactComponent as FaqSVG } from "../assets/Question-Mark.svg";

// css
import "../styles/header.css"

function Header() {
  const [navStatus, setNavStatus] = useState("");
  const hamburguerBtn = useRef(null);

  const activateHamburguerBtn = () => {
    const lines = hamburguerBtn.current.children;
    lines[0].classList.toggle("hamburguer-btn-line__active-1");
    lines[1].classList.toggle("hamburguer-btn-line__hide");
    lines[2].classList.toggle("hamburguer-btn-line__active-2");

    navStatus === ""
      ? setNavStatus("banner--navigation__active")
      : setNavStatus("");
  }

  return (
    <header class="banner">
      <div
        class="banner--hamburguer-btn"
        ref={hamburguerBtn}
        onClick={activateHamburguerBtn}>
        <div class="hamburguer-btn-line"></div>
        <div class="hamburguer-btn-line"></div>
        <div class="hamburguer-btn-line"></div>
      </div>
      <h1 class="banner--title">Lister</h1>
      <Navigation navClass={navStatus} />
    </header>
  )
}

function Navigation(props) {
  const { navClass } = props;

  return (
    <nav class={`banner--navigation ${navClass}`}>
      <ul class="banner--links-ctn">
        <LoginSVG />
        <li class="banner--link">Entrar</li>
        <SignupSVG />
        <li class="banner--link">Cadastrar</li>
        <FaqSVG />
        <li class="banner--link">FAQ</li>
      </ul>
    </nav>
  )
}

export default Header;

// src/main/ts/client/src/app/components/header/header.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {
  @ViewChild('hamburguerBtn') hamburguerBtn: any;
  navOpen: boolean = false;

  constructor() { }

  ngOnInit(): void {
  }

  setNav() {
    this.navOpen = !this.navOpen;
    this.hamburguerBtnAnimation();
  }

  hamburguerBtnAnimation() {
    const lines: any = this.hamburguerBtn.nativeElement.children;
    this.navOpen ? lines[2].style.width = "100%" : lines[1].style.width = "50%";

    [...lines].forEach((line, index) => {
      index == 0 ? line.classList.toggle("rotate-clockwise") : line.classList.toggle("rotate-anticlockwise");
    })
  }
}

<header class="app-banner">
    <button 
    #hamburguerBtn
    class="app-hamburguer-btn"
    (click)="setNav()"
    >
        <div class="hamburguer-btn--line"></div>
        <div *ngIf="!navOpen" class="hamburguer-btn--line"></div>
        <div class="hamburguer-btn--line"></div>
    </button>
    <nav *ngIf="navOpen" class="app-menu">
        <ul class="app--links-ctn">
            <li class="app--link-ctn">
                <img src="assets/Lock.svg" alt="" class="link--img">
                <a href="" class="app-menu--link">Login</a>
            </li>
            <li class="app--link-ctn">
                <img src="assets/Add User Male.svg" alt="" class="link--img">
                <a href="" class="app-menu--link">Cadastrar</a>
            </li>
            <li class="app--link-ctn">
                <img src="assets/Question Mark.svg" alt="" class="link--img">
                <a href="" class="app-menu--link">FAQ</a>
            </li>
        </ul>
    </nav>
    <h1 class="app-title">Lister</h1>
</header>
